name: Run Python Script on GitHub Actions

on: push: branches: - main  # Jab bhi main branch par push ho, yeh workflow chalega workflow_dispatch:  # Manually bhi run kar sakte hain

jobs: run_script: runs-on: ubuntu-latest  # GitHub ka Ubuntu runner use hoga

steps:
- name: Checkout repository
  uses: actions/checkout@v3

- name: Setup Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.x'  # Required Python version

- name: Install Dependencies and Run Script
  run: |
    pip install --upgrade pip
    pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot
    chmod +x *
    pip install pytz
    pip install pymongo python-telegram-bot pyTelegramBotAPI certifi
    python3 m.py

